import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import nextPlugin from '@next/eslint-plugin-next';

export default [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'playwright-report/**',
      // Generated by Next.js on build; regenerated, never hand-edited.
      'next-env.d.ts',
      // Generated by `npm run db:types`.
      'src/types/database.ts',
      // Supabase CLI scratch space, and the local PostgreSQL data directory.
      'supabase/.temp/**',
      'supabase/.branches/**',
      '.localdb/**',
    ],
  },
  js.configs.recommended,
  {
    // Next.js configuration runs in Node, so its runtime globals must be
    // declared explicitly while keeping `no-undef` enabled.
    files: ['next.config.mjs'],
    languageOptions: {
      globals: {
        process: 'readonly',
      },
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: { '@typescript-eslint': tseslint, '@next/next': nextPlugin },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      // TypeScript resolves identifiers itself and reports undefined ones with
      // full type information. Leaving no-undef on for .ts files duplicates that
      // and produces false positives for ambient globals (process, URL, React).
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/supabase/admin*'],
              message:
                'The service-role client bypasses RLS. Import it only inside server-side admin routines, never in components.',
            },
          ],
        },
      ],
    },
  },

  {
    // Node scripts, not application code. `no-undef` is on for these (there is
    // no type checker doing the job instead), so Node's globals are declared
    // rather than the rule being switched off.
    files: ['scripts/**/*.mjs', 'scripts/**/*.js'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
      },
    },
  },
];
