// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teacher-growth-redesign/OrganisedDashboard.tsx": () => import("../components/mockups/teacher-growth-redesign/OrganisedDashboard.tsx")
};
